config/routes.rb
Rails.application.routes.draw do



resources:students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord

# def sendEmail
#   Sendemail.send(self)
#
#   puts "Hi"
#
# end

validates :firstname, :lastname,  presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    @person = Person.new
end

def create
  @person = Person.new(params[:person])
  if @person.save
    redirect_to new_person_path

  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

#indexing all Students
def index
  @students = Student.all
end

def show
   @student = Student.find(params[:id])
 end
# end

#associated with students/new
  def new
    @student = Student.new
  end

# def index
#    @students = Student.all
#
def edit
  @student = Student.find(params[:id])
end
# end

#by default hitting submit will attempt to post to the uri associated with create, which is /students
#the redirect ensures you get back to a fresh new form
#notice you can use the parameters you entered on the form
  def create
    @student = Student.new(params[:student].permit(:firstname, :lastname))
    if @student.save
      redirect_to(@student)#new_student_path
    else
        render 'new'
    end
  end


  def update
    @student = Student.find(params[:id])
    if @student.update(params[:student].permit(:firstname, :lastname))
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to(students_path)
  end

end

#
# class StudentsController < ApplicationController
#   def new
#     @student = Student.new
#     @students = Student.all
#   end
#
#   def create
#     @student = Student.new(student_params)
#  if @student.save
#    redirect_to new_student_path
#  end
#   end
#
#   def student_params
#     params.require(:student).permit(:firstname, :lastname)
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/new.html.erb
Enter new person information

<hr>
<% form_for @student do |f| -%>

 <%= f.text_field :firstname :firstname %><br />
 <%= f.text_field :lastname :lastname %><br />
 <%= f.submit%>
<% end -%>

app/views/students/edit.html.erb
Enter new student information

#handling errors when creating new students
<% if @student.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@student.errors.count, "error") %>
       prohibited this student from being created:
     </h2>
     <ul>
       <% @student.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

<hr>
<%= form_for @student do |f| -%>

 First Name: <%= f.text_field :firstname  %><br />
 Last Name: <%= f.text_field :lastname %><br />
 <%= f.submit%>
<% end -%>


<!-- <hr>
Display Students:
<br />
<% if !@students.blank? %>
  <% for item in @students %>
    <%= item.firstname %> <%= item.lastname %> <br />
    <% end %>
    <% else %>
  <% end %> -->

app/views/students/index.html.erb
<h2>Welcome to your Student Tracker</h2>

<br/>
<%= link_to 'Create Student Record', new_student_path %>




<h3>Listing all students</h3>

<table>
  <tr>
    <th>first</th>
    <th>last</th>
    <th>View</th>
    <th> Edit </th>
  </tr>

  <% @students.each do |student| %>
    <tr>
      <td><%= student.firstname %></td>
      <td><%= student.lastname %></td>
      <td><%= link_to 'Show', student_path(student) %></td>
       <td><%= link_to 'Edit', edit_student_path(student) %></td>
       <td><%= link_to 'Delete', student_path(student),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/students/new.html.erb
Enter new student information

#handling errors when creating new students
<% if @student.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@student.errors.count, "error") %>
       prohibited this student from being created:
     </h2>
     <ul>
       <% @student.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>





<hr>
<%= form_for @student do |f| -%>

 First Name: <%= f.text_field :firstname  %><br />
 Last Name: <%= f.text_field :lastname %><br />
 <%= f.submit%>
<% end -%>


<!-- <hr>
Display Students:
<br />
<% if !@students.blank? %>
  <% for item in @students %>
    <%= item.firstname %> <%= item.lastname %> <br />
    <% end %>
    <% else %>
  <% end %> -->

app/views/students/show.html.erb
<<hr>
Student Record:
  <%= @student.firstname %> <%= @student.lastname %>

  <br/>
  <br/>
  <%= link_to 'Edit', edit_student_path(@student) %> |
  <%= link_to 'Back to All Students', students_path %>